# Generated by Django 4.1.2 on 2022-11-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombres')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('contraseña', models.CharField(max_length=20, verbose_name='email')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academica.docente')),
            ],
        ),
    ]
